/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppContent {}
  interface AppFind {}
  interface AppFooter {}
  interface AppGallery {}
  interface AppLandingPage {}
  interface AppRoot {}
}

declare global {


  interface HTMLAppContentElement extends Components.AppContent, HTMLStencilElement {}
  var HTMLAppContentElement: {
    prototype: HTMLAppContentElement;
    new (): HTMLAppContentElement;
  };

  interface HTMLAppFindElement extends Components.AppFind, HTMLStencilElement {}
  var HTMLAppFindElement: {
    prototype: HTMLAppFindElement;
    new (): HTMLAppFindElement;
  };

  interface HTMLAppFooterElement extends Components.AppFooter, HTMLStencilElement {}
  var HTMLAppFooterElement: {
    prototype: HTMLAppFooterElement;
    new (): HTMLAppFooterElement;
  };

  interface HTMLAppGalleryElement extends Components.AppGallery, HTMLStencilElement {}
  var HTMLAppGalleryElement: {
    prototype: HTMLAppGalleryElement;
    new (): HTMLAppGalleryElement;
  };

  interface HTMLAppLandingPageElement extends Components.AppLandingPage, HTMLStencilElement {}
  var HTMLAppLandingPageElement: {
    prototype: HTMLAppLandingPageElement;
    new (): HTMLAppLandingPageElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };
  interface HTMLElementTagNameMap {
    'app-content': HTMLAppContentElement;
    'app-find': HTMLAppFindElement;
    'app-footer': HTMLAppFooterElement;
    'app-gallery': HTMLAppGalleryElement;
    'app-landing-page': HTMLAppLandingPageElement;
    'app-root': HTMLAppRootElement;
  }
}

declare namespace LocalJSX {
  interface AppContent {}
  interface AppFind {}
  interface AppFooter {
    'onChangeDisplayIndex'?: (event: CustomEvent<any>) => void;
  }
  interface AppGallery {}
  interface AppLandingPage {}
  interface AppRoot {}

  interface IntrinsicElements {
    'app-content': AppContent;
    'app-find': AppFind;
    'app-footer': AppFooter;
    'app-gallery': AppGallery;
    'app-landing-page': AppLandingPage;
    'app-root': AppRoot;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-content': LocalJSX.AppContent & JSXBase.HTMLAttributes<HTMLAppContentElement>;
      'app-find': LocalJSX.AppFind & JSXBase.HTMLAttributes<HTMLAppFindElement>;
      'app-footer': LocalJSX.AppFooter & JSXBase.HTMLAttributes<HTMLAppFooterElement>;
      'app-gallery': LocalJSX.AppGallery & JSXBase.HTMLAttributes<HTMLAppGalleryElement>;
      'app-landing-page': LocalJSX.AppLandingPage & JSXBase.HTMLAttributes<HTMLAppLandingPageElement>;
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
    }
  }
}


